services:
  - type: web
    name: hirevyom-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    routes:
      - type: rewrite
        source: "/*"
        destination: /index.html
